### ISSUE TITLE
Move to jupyter-renderers

### ISSUE THREAD

**Issue by gnestor** [jasongrout/jupyterlab-fasta#13]
Should we move this to https://github.com/jupyterlab/jupyter-renderers?

**Comment by jasongrout** [comment]
I'm okay with that.

**Comment by gnestor** [comment]
https://github.com/jupyterlab/jupyter-renderers/pull/60

**Comment by gnestor** [comment]
Merged! I just published `@jupyterlab/fasta-extension` to npm so I think we can deprecate this repo.
