### ISSUE TITLE
Deprecate npm package

### ISSUE THREAD

**Issue by vidartf** [jasongrout/jupyterlab-fasta#16]

**Comment by jasongrout** [comment]
Actually, the `jupyterlab-fasta` package was never published to npm (and is marked as private in the package.json, so it can't be published) since we weren't sure about the naming.

**Comment by jasongrout** [comment]
(See #2.)

**Comment by jasongrout** [comment]
I also just moved this repo to the jupyter-attic org, so I think everything should be good now.

**Comment by jasongrout** [comment]
(and removed the keywords so it doesn't show up in searches, labeled it in the description in readme, etc.)
