### ISSUE TITLE
Newick Files Don't Open - Tab hangs

### ISSUE THREAD

**Issue by JenCabral** [jasongrout/jupyterlab-fasta#8]
Attempting to open a newick file causes the tab it is attempting to open in to hang and not show any progress. Tested with a simple 1 kb tree and a more complete 3 kb tree (waited ~20 minutes for both files without success). Neither opened and I am unable to close the tabs that were trying to open the files. Both files can be opened with the editor without issue. 

On the Jupyter Hub version I have running on a server, refreshing the page closes the tab, but on the local instance of non-hub, restarting jupyter lab did not remove the tab nor did refreshing the page. Will update issue if I find a way to close the Newick tabs

**Comment by jasongrout** [comment]
Thanks. We just use msa to render files. It seems like they have some sort of support for newick: https://github.com/wilzbach/msa/search?utf8=%E2%9C%93&q=newick&type=
It's very possible that (a) we don't use it correctly (the documentation for msa is not very complete), or (b) msa maybe doesn't handle newick very well? I think (a) is more likely, so I think we should remove advertised support for newick until some more knowledgable about msa and/or newick can look at it.
